name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org/"

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check existing version
        run: |
          existing_version=$(npm show refirebase version)
          target_version=$(jq -r '.version' package.json)
          if [ "$existing_version" == "$target_version" ]; then
            echo "Version $target_version already exists. Please update the version in package.json."
            exit 1
          fi

      - name: Build and Publish package
        run: |
          if ! bun run build; then
            echo "Error: Failed to build the package."
            exit 1
          fi

          # Login to NPM
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm login --registry=https://registry.npmjs.org/ --auth-type=legacy

          # Then publish with force flag
          if ! npm publish --access public --force; then
            echo "Error: Failed to publish the package."
            echo "Possible reasons:"
            echo "- You might be trying to publish an already existing version."
            echo "- Check your permissions for the npm registry."
            echo "- Ensure your package.json is correctly configured."
            exit 1
          fi

          echo "Package published successfully. Version: $(jq -r '.version' package.json)"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
